### PR TITLE
Update submodules so that stShift tests are executed

### PR DESCRIPTION
**Pull request by pirapira**
Replaces #16.

### CODE REVIEW

**Comment by pirapira** [comment]
Ah, wait, this one is not ready.

**Comment by pirapira** [comment]
Should be ready now.

**Comment by winsvega** [comment]
why don't you simlink all folders but test?

**Comment by pirapira** [comment]
Just lazy, but I can do it now (or after lunch).

**Comment by pirapira** [comment]
Merge?

**Comment by winsvega** [comment]
how do you avoid conflicts for 
/test/  testeth  source
and 
/@'cpp-ethereum/test/ testeth source?

**Comment by pirapira** [comment]
I never see `/cpp-ethereum/test/ testeth` source.

**Comment by pirapira** [comment]
It's going to disappear, I was told.

**Review by winsvega — APPROVED** [review]
ok

**Pull request merged**
